spring:
  application:
    name: memoryvault
  datasource:
    url: jdbc:postgresql://localhost:1236/memoryvalutdb
    username: muser
    password: "denji@0086"
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE 'Asia/Kolkata'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        jdbc:
          time_zone: Asia/Kolkata
  jackson:
    time-zone: Asia/Kolkata
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

